apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  selector:
    app: pgadmin
  ports:
  - name: {{ .Values.Lab.PgAdmin.HttpPort.name }}
    port: {{ .Values.Lab.PgAdmin.HttpPort.port }}
    targetPort: {{ .Values.Lab.PgAdmin.HttpPort.targetPort }}
    nodePort: {{ .Values.Lab.PgAdmin.HttpPort.nodePort }}
  type: NodePort