apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: postgres
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: postgres
      release: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: postgres
        release: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.postgres.securityContext | nindent 8 }}
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        imagePullPolicy: {{ .Values.postgres.imagePullPolicy |  default "IfNotPresent" }}
        resources:
          {{- toYaml .Values.postgres.resources | nindent 12 }}        
        ports:
        - containerPort: {{ .Values.postgres.service.port }}
          name: postgresql
        env:
        - name: POSTGRES_USER
          value: {{ default "postgres" .Values.postgres.postgresUser | quote }}
        - name: POSTGRES_PASSWORD
          value: "password"
          # valueFrom:
          #   secretKeyRef:
          #     name: {{ .Values.postgres.postgresPassword.name }}
          #     key: {{ .Values.postgres.postgresPassword.passwordKey }}
        - name: POSTGRES_DB
          value: {{ quote .Values.postgres.postgresDB }}
  #         volumeMounts:
  #           - name: postgresql-data
  #             mountPath: /var/lib/postgresql/data
  # volumeClaimTemplates:
  #   - metadata:
  #       name: postgresql-data
  #     spec:
  #       accessModes: [ "ReadWriteOnce" ]
  #       storageClassName: {{ .Values.postgres.storage.storageClassName | quote }}
  #       resources:
  #         requests:
  #           storage: {{ .Values.postgres.storage.size | quote }}
