apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: {{ .replicaCount }}
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: {{ .Values.Lab.PgAdmin.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.Lab.PgAdmin.HttpPort.port }}
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value:  {{ quote .Values.Lab.PgAdmin.env.email }}
        - name: PGADMIN_DEFAULT_PASSWORD
          value: {{ quote .Values.Lab.PgAdmin.env.password }}
