apiVersion: v1
kind: Service
metadata:
  name: image-repository
spec:
  type: ClusterIP  # Or LoadBalancer for external access
  selector:
    app: image-repository
  ports:
  - protocol: TCP
    port: 5000     # Expose on HTTPS port externally
    targetPort: 5000  # Forward to the registry container's port
    name: https