apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    date: {{ now | htmlDate }}
    version: {{ .Chart.Version | quote }}
spec:
  type: ClusterIP  # Or LoadBalancer for external access
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: TCP
    port: 5000     # Expose on HTTPS port externally
    targetPort: 5000  # Forward to the registry container's port
    name: https