apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: stone-data-lake
spec:
  selector:
   matchLabels:
    app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
#          image: postgres:14.5
          image: localhost:5000/data-lake-postgres
          imagePullPolicy: "IfNotPresent"
          env:
           - name: POSTGRES_USER
             valueFrom:
               secretKeyRef:
                 name: stone-data-lake-secret
                 key: postgres_root_username
           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: stone-data-lake-secret
                 key: postgres_root_password
           - name: POSTGRES_DB
             valueFrom:
               configMapKeyRef:
                 name: stone-data-lake-configmap
                 key: postgres-dbname
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pvc