apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: stone-data-lake
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
#    path: /run/desktop/mnt/host/c/Users/c.stone/Documents/GitHub/data_lake_example/postgres/data # Hard coded
#    path: # This doesn't work
#      valueFrom:  
#        configMapKeyRef:
#          name: stone-data-lake-configmap
#          key: postgres-db-location
    path: ${postgres_local_path}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
  volumeMode: Filesystem 