{{- $object := .Values.nifi -}}
{{- $_ := set $object "version" .Values.version -}}
{{- if not $object.namespace -}}
    {{- $_ := set $object "namespace" .Values.namespace -}}
{{- end }}
{{- /* Add Services if they are required */}}
{{- template "mychart.service" $object }}

{{- if $object.enabled }}
---
#apiVersion: extensions/v1beta1
apiVersion: networking.k8s.io/v1
kind: Ingress
{{- template "mychart.metadata" $object }}
spec:
  rules:
  - host: nifi
    http:
      paths:
      - path: /nifi
        pathType: Prefix
        backend:
          service:
            name: nifi-service
            port:
              number: 8180
---
# https://hub.docker.com/r/apache/nifi
apiVersion: apps/v1
kind: StatefulSet
{{- template "mychart.metadata" $object }}
spec:
  replicas: {{ $object.replicas }}
  selector:
    matchLabels:
      app: {{ $object.name }}
  serviceName: {{ $object.name }}
  template:
    metadata:
      labels:
        app: {{ $object.name }}
    spec:
      containers:
        - name: {{ $object.name }}
          image: {{ $object.image }}
          imagePullPolicy: {{ $object.imagePullPolicy }}
          resources:
            requests:
              cpu: "2000m"
              memory: "2Gi"
            limits:
              cpu: "4000m"
              memory: "4Gi"
              nvidia.com/gpu: "0"
          ports:
          - containerPort: 31000
            name: http-port
          - containerPort: 31001
            name: https-port
          - containerPort: 31011
            name: tcp-port1
          - containerPort: 31012
            name: tcp-port2
          - containerPort: 31013
            name: tcp-port3
          - containerPort: 31014
            name: tcp-port4
          - containerPort: 31021
            name: udp-port1
          - containerPort: 31022
            name: udp-port2
          - containerPort: 31023
            name: udp-port3
          - containerPort: 31024
            name: udp-port4
          env:
          {{- range $object.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
          # volumeMounts:
          # - name: nifi-logs-pv
          #   mountPath: /opt/nifi/nifi-current/logs
          # - name: nifi-content-pv
          #   mountPath: /opt/nifi/nifi-current/content-repository
          # - name: nifi-flowfile-pv
          #   mountPath: /opt/nifi/nifi-current/flowfile-repository
          # - name: nifi-db-pv
          #   mountPath: /opt/nifi/nifi-current/database-repository
          # - name: nifi-provenance-pv
          #   mountPath: /opt/nifi/nifi-current/provenance-repository
        # volumes:
        # - name: nifi-logs-pv
        #   persistentVolumeClaim:
        #    claimName: nifi-logs-pvc
        # - name: nifi-content-pv
        #   persistentVolumeClaim:
        #    claimName: nifi-content-pvc
        # - name: nifi-flowfile-pv
        #   persistentVolumeClaim:
        #     claimName: nifi-flowfile-pvc
        # - name: nifi-db-pv
        #   persistentVolumeClaim:
        #     claimName: nifi-db-pvc
        # - name: nifi-provenance-pv
        #   persistentVolumeClaim:
        #     claimName: nifi-provenance-pvc

{{- /* Add PersistentVolumeClaim if they are required */}}
{{- range $object.pvc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- template "mychart.labels" $object }}
  name: {{ .name }}
  namespace: {{ $object.namespace }}
spec:
  accessModes: {{ .accessModes }}
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}

{{- end }}

{{/*
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nifi-ingress
spec:
  rules:
  - host: nifi
    http:
      paths:
      - path: /nifi
        pathType: Prefix
        backend:
          service:
            name: nifi-service
            port:
              number: 8180
---
# Logs persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nifi
  name: {{ .Release.Name }}-nifi-logs-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
# content repo persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nifi
  name: {{ .Release.Name }}-nifi-content-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi      
---
# FlowFile repo persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nifi
  name: {{ .Release.Name }}-nifi-flowfile-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi      
---
# database repo persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nifi
  name: {{ .Release.Name }}-nifi-db-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi      
---
# provenance repo persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nifi
  name: {{ .Release.Name }}-nifi-provenance-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi      
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nifi
spec:
  selector:
    app: nifi
  type: NodePort  # Use LoadBalancer if you're on a cloud that supports it
  ports:
  - protocol: TCP
    #port: 8080
    port: 31000
    name: http-port
    nodePort: 31000
  - protocol: TCP
    #port: 8443
    port: 31001
    name: https-port
    nodePort: 31001
  - protocol: TCP
    port: 31011
    name: tcp-port1
    nodePort: 31011
  - protocol: TCP
    port: 31012
    name: tcp-port2
    nodePort: 31012
  - protocol: TCP
    port: 31013
    name: tcp-port3
    nodePort: 31013
  - protocol: TCP
    port: 31014
    name: tcp-port4
    nodePort: 31014
  - protocol: UDP
    port: 31021
    name: udp-port1
    nodePort: 31021
  - protocol: UDP
    port: 31022
    name: udp-port2
    nodePort: 31022
  - protocol: UDP
    port: 31023
    name: udp-port3
    nodePort: 31023
  - protocol: UDP
    port: 31024
    name: udp-port4
    nodePort: 31024
  # type: LoadBalancer 

# apiVersion: v1
# kind: Service
# metadata:
#   name: nifi-service
# spec:
#   selector:
#     app: nifi
#   ports:
#   - protocol: TCP
#     port: 11434
#     targetPort: 11434
#   - protocol: UDP
#     port: 11434
#     targetPort: 11434
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-nifi
  labels:
    app: nifi
spec:
  replicas: {{ .replicaCount }}
  serviceName: nifi
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec: 
      containers:
      - name: nifi-container
        image: {{ .Values.Lab.Nifi.image }}
        imagePullPolicy: IfNotPresent
        resources: 
          requests:
            cpu: "2000m"
            memory: "2Gi"
          limits:
            cpu: "4000m"
            memory: "4Gi"
            nvidia.com/gpu: "0"
        volumeMounts:
        - name: nifi-logs-pv
          mountPath: /opt/nifi/nifi-current/logs
        - name: nifi-content-pv
          mountPath: /opt/nifi/nifi-current/content-repository
      #   - name: nifi-flowfile-pv
      #     mountPath: /opt/nifi/nifi-current/flowfile-repository
      #   - name: nifi-db-pv
      #     mountPath: /opt/nifi/nifi-current/database-repository
      #   - name: nifi-provenance-pv
      #     mountPath: /opt/nifi/nifi-current/provenance-repository
        ports:
        - containerPort: {{ .Values.Lab.Nifi.HttpPort.port }}
          name: {{ .Values.Lab.Nifi.HttpPort.name }}
        - containerPort: {{ .Values.Lab.Nifi.HttpsPort.port }}
          name: {{ .Values.Lab.Nifi.HttpsPort.name }}
        - containerPort: 31011
          name: tcp-port1
        - containerPort: 31012
          name: tcp-port2
        - containerPort: 31013
          name: tcp-port3
        - containerPort: 31014
          name: tcp-port4
        - containerPort: 31021
          name: udp-port1
        - containerPort: 31022
          name: udp-port2
        - containerPort: 31023
          name: udp-port3
        - containerPort: 31024
          name: udp-port4
        env:
        - name: NIFI_WEB_HTTPS_HOST
          value: {{ quote .Values.Lab.Nifi.env.host }}
        - name: SINGLE_USER_CREDENTIALS_USERNAME
          value: {{ quote .Values.Lab.Nifi.env.user }}
        - name: SINGLE_USER_CREDENTIALS_PASSWORD
          value: {{ quote .Values.Lab.Nifi.env.password }}
        - name: NIFI_WEB_HTTPS_PORT
          value: {{ quote .Values.Lab.Nifi.HttpsPort.port }}
        - name: NIFI_WEB_HTTP_PORT
          value: {{ quote .Values.Lab.Nifi.HttpPort.port }}
      #   - name: VERSION
      #     value: "1.10"
      volumes:
      - name: nifi-logs-pv
        persistentVolumeClaim: 
          claimName: {{ .Release.Name }}-nifi-logs-pvc
      - name: nifi-content-pv
        persistentVolumeClaim: 
          claimName: {{ .Release.Name }}-nifi-content-pvc
      # - name: nifi-flowfile-pv
      #   persistentVolumeClaim: 
      #     claimName: {{ .Release.Name }}-nifi-flowfile-pvc
      # - name: nifi-db-pv
      #   persistentVolumeClaim: 
      #     claimName: {{ .Release.Name }}-nifi-db-pvc
      # - name: nifi-provenance-pv
      #   persistentVolumeClaim: 
      #     claimName: {{ .Release.Name }}-nifi-provenance-pvc
*/}}