apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.Lab.Jupyter.volume_name }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - {{ .Values.Lab.persistent_volume.access_modes }}
  persistentVolumeReclaimPolicy: {{ .Values.Lab.persistent_volume.persistent_volume_reclaim_policy }}
  storageClassName: {{ .Values.Lab.persistent_volume.storage_class_name }} 
  local:
    path: {{ .Values.Lab.persistent_volume.volume_path }}/{{ .Values.Lab.Jupyter.volume_folder_name }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lima-rancher-desktop
