apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.Lab.Jupyter.name }}-pvc
spec:
  accessModes:
    - {{ .Values.Lab.persistent_volume.access_modes }}
  resources:
    requests:
      storage: {{ .Values.Lab.Jupyter.volume.size }} 
  storageClassName: {{ .Values.Lab.persistent_volume.storage_class_name }} 