kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.Lab.Jupyter.name }}
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
  - protocol: {{ .Values.Lab.Jupyter.HttpPort.protocol }}
    nodePort: {{ .Values.Lab.Jupyter.HttpPort.nodePort }}
    port: {{ .Values.Lab.Jupyter.HttpPort.port }}
