apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.Lab.Jupyter.name }}
  labels:
    app: {{ .Values.Lab.Jupyter.label }}
spec:
  replicas: {{ .replicaCount }}
  serviceName: {{ .Values.Lab.Jupyter.name }}
  selector:
    matchLabels:
      app: {{ .Values.Lab.Jupyter.selector_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Lab.Jupyter.selector_name }}
    spec:
      containers:
        - name: {{ .Values.Lab.Jupyter.name }}
          ports:
            - containerPort: {{ .Values.Lab.Jupyter.HttpPort.port  }}
              name: {{ .Values.Lab.Jupyter.HttpPort.name  }}
              protocol: {{ .Values.Lab.Jupyter.HttpPort.protocol }}
          env:
          - name: JUPYTER_PORT  
            value: {{ quote .Values.Lab.Jupyter.HttpPort.port }}
          - name: RESTARTABLE
            value: "yes"
          image: {{ .Values.Lab.Jupyter.image }}
          imagePullPolicy: "IfNotPresent"
          volumeMounts: 
          - mountPath: {{ .Values.Lab.Jupyter.volume.mount_path }} 
            name: {{ .Values.Lab.Jupyter.name }}-pvc
      volumes:
      - name: {{ .Values.Lab.Jupyter.name }}-pvc
        persistentVolumeClaim:
          claimName: {{ .Values.Lab.Jupyter.name }}-pvc