apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-jupyter
  labels:
    app: jupyter
spec:
  replicas: {{ .replicaCount }}
  serviceName: jupyter
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          ports:
            - containerPort: {{ .Values.Lab.Jupyter.HttpPort.port  }}
              name: {{ .Values.Lab.Jupyter.HttpPort.name  }}
              protocol: {{ .Values.Lab.Jupyter.HttpPort.protocol }}
          env:
          - name: JUPYTER_PORT  
            value: {{ quote .Values.Lab.Jupyter.HttpPort.port }}
          - name: RESTARTABLE
            value: "yes"
          image: {{ .Values.Lab.Jupyter.image }}
          volumeMounts: 
          - mountPath: /home/jovyan/work
            name: jupyter-pvc
      volumes:
      - name: jupyter-pvc
        persistentVolumeClaim:
          claimName: jupyter-pvc
        #readOnly: false
      # volumes: 
      # - name: jupyter-work-volume
      #   hostPath:
      #     path: work