apiVersion: v2
name: test-lab
description: A helm chart to deploy a basic lab that I use for testing data-science
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
- name: github.com/cstone157
