# -----------------------------------------------------------
# Release:
# -----------------------------------------------------------
global:
  namespace: home-lab
  version: "0.1a"

jupyter:
  enabled: true

keycloak:
  enabled: false

mongo:
  enabled: false

mongo-express:
  enabled: false

nifi:
  enabled: false

ollama:
  enabled: false

pgadmin:
  enabled: false

postgres:
  enabled: false

rstudio:
  enabled: false

webui:
  enabled: false
