# -----------------------------------------------------------
# Release:
# -----------------------------------------------------------
global:
  namespace: home-lab
  version: "0.1a"

home-lab-jupyter:
  jupyter:
    enabled: false