# -----------------------------------------------------------
# Release:
# -----------------------------------------------------------
global:
  namespace: home-lab
  version: "0.1a"

jupyter:
  enabled: true