apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      serviceAccountName: spark-jupyter-sa # Attaching the RBAC account
      containers:
      - name: jupyterlab
        # image: jupyter/pyspark-notebook:spark-3.5.0 # Use a specific Spark version
        image: jupyter/pyspark-notebook:spark-3.3.1 # Switched to version 3.3.1 since there is no apache/spark image for 3.5.0
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-service
  namespace: default
spec:
  type: LoadBalancer # Use NodePort or ClusterIP if not on a Cloud Provider
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: jupyterlab