apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc # Consistent name for the claim
spec:
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany if your storage supports it
  resources:
    requests:
      storage: 10Gi #  Adjust the storage size as needed
  storageClassName: standard # Or your preferred storage class