# ------------------------------------------------------------------------------
# JupyterLab :
# ------------------------------------------------------------------------------
enabled: false
name: jupyter
image: jupyter/minimal-notebook:notebook-7.0.6
imagePullPolicy: IfNotPresent
replicas: 1
env:
  - name: JUPYTER_PORT  
    value: "8888"
  - name: RESTARTABLE
    value: "yes"
service_type: NodePort
service:
  - protocol: TCP
    nodePort: 30020
    port: 8888
labels:
  category: analysis
# persistentVolume:
#   enabled: false
#   volumes:
#   - name: jupyter-local
#     mountPath: /home/jovyan/work
#     accessModes: ["ReadWriteOnce"]
#     storage: 5Gi
#     persistentVolumeReclaimPolicy: Delete
#     storageClassName: local-path                  # **ONLY FOR TESTING!  NOT FOR PRODUCTION!**
#     hostPath: C:\k8\local-storage\jupyter         # **ONLY FOR TESTING!  NOT FOR PRODUCTION!**
