apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openwebui
spec:
  type: NodePort  # Use LoadBalancer if you're on a cloud that supports it
  selector:
    app: open-webui
  ports:
    - protocol: {{ .Values.Lab.WebUi.HttpPort.protocol }}
      port: {{ .Values.Lab.WebUi.HttpPort.port }}
      targetPort: {{ .Values.Lab.WebUi.HttpPort.targetPort }}
      nodePort: {{ .Values.Lab.WebUi.HttpPort.nodePort }}