apiVersion: v1
kind: PersistentVolume
metadata:
#   name: rstudio-local-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage 
#   local:
#     path: /home/cstone/rstudio-data 
  name: {{ .Values.Lab.RStudio.name }}-local-pv
spec:
  capacity:
    storage: {{ .Values.Lab.RStudio.volume.size }}
  accessModes:
    - {{ .Values.Lab.persistent_volume.access_modes }}
  persistentVolumeReclaimPolicy: {{ .Values.Lab.persistent_volume.persistent_volume_reclaim_policy }}
  storageClassName: {{ .Values.Lab.persistent_volume.storage_class_name }} 
  local:
    path: {{ .Values.Lab.persistent_volume.volume_path }}/{{ .Values.Lab.RStudio.volume.folder_name }}
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - lima-rancher-desktop
  # nodeSelector:
  #   matchLabels:
  #     kubernetes.io/hostname: lima-rancher-desktop 
